# Generated by Django 5.2 on 2025-05-30 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nin_number', models.CharField(max_length=18, unique=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('birthday', models.DateField()),
                ('state', models.CharField(max_length=30)),
                ('family_name', models.CharField(max_length=30)),
                ('full_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('country', models.CharField(max_length=56)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
    ]
