# Generated by Django 5.2 on 2025-05-31 10:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('code', models.CharField(max_length=6)),
                ('full_name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=128)),
                ('nin_number', models.CharField(max_length=18)),
                ('phone_number', models.CharField(max_length=15)),
                ('birthday', models.DateField()),
                ('state', models.CharField(max_length=30)),
                ('family_name', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=56)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
