# Generated by Django 5.2 on 2025-06-01 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_pendingclient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='country',
            new_name='gender',
        ),
        migrations.RenameField(
            model_name='pendingclient',
            old_name='country',
            new_name='gender',
        ),
    ]
