# Generated by Django 5.2 on 2025-07-05 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_alter_service_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_type',
            field=models.CharField(choices=[('passport', 'إستخراج وثائق رسمية - جواز السفر'), ('id_card', 'إستخراج وثائق رسمية - بطاقة الهوية الوطنية البيومترية'), ('nationality', 'إستخراج وثائق رسمية - الجنسية'), ('bills', 'دفع الفواتير و المستحقات الرسمية'), ('visas', 'تجهيز طلبات و ملفات مختلفة - تأشيرات'), ('consulting', 'الإستشارات الإدارية'), ('notary_lawyer', 'مكاتب التوثيق و المحاماة'), ('insurance', 'خدمات التأمين الصحي و تأمين السيارات'), ('business_license', 'إصدار رخص تجارية و توفير وكيل خدمات المواطن'), ('construction_license', 'إصدار رخصة البناء'), ('other', 'طلبات أخرى')], max_length=20),
        ),
    ]
